- name: PLAY-1
  hosts: web
  become: yes
  tasks:
  - name: PLAY-1 & TASK-1
    ansible.builtin.debug:
      msg: "Hi this is  PLAY-1 & TASK-1"

- name: PLAY-2
  hosts: web
  become: yes
  tasks:
  - name: PLAY-2 & TASK-2
    ansible.builtin.debug:
      msg: "Hi this is  PLAY-2 & TASK-2"