- name: variables
  hosts: web
  vars:
    Course: Terraform
    Trainer: Mani
    Duration: "15hrs"
  tasks:
  vars:
    Course: Ansible
    Trainer: ManiKanta
    Duration: "25hrs"
  - name: Print info
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}}...."

  - name: Print info
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}}...."