- name: variables
  hosts: web
  vars:
    Course: Terraform
    Trainer: Mani
    Duration: "15hrs"
  tasks:
  - name: Print task level Vars
    vars:
      Course: Ansible
      Trainer: ManiKanta
      Duration: "25hrs"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}}...."

  - name: Print play level Vars
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}}...."