# If we not found any module for our requirement then use: COMMAND / SHELL MODULE

- name: ansible command vs shell module
  hosts: local
  connection: local
  tasks:
  - name: shell vs command module test
    #ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{ users_output }}"

  - name: shell module test with files
    ansible.builtin.shell: ls -ltr > files.txt
    register: files_output

  - name: print output of files
    ansible.builtin.debug:
      msg: "{{ files_output }}"

# command (use for normal commands)
# =======
# simple commands you can execute
# more secure, bcz you can't get complete shell env of the remote server.
# > , | will not work here

# shell  (use for complex scripts)
# ======
# you will get access to entire environment of the server...
# less secure
# >, | works here  