- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug: 
      msg: "Hai hello: {{ item }}"  # item is reserved keywork in ansible
    loop:
    - Mani
    - Kanta
    - Reddy