- name: installing packages
  hosts: local
  connection: local
  tasks:
  - name: Installing list of packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - python3
