# Loops

- name: loops in ansible
  hosts: local
  connection: local
  tasks:
  - name: print names in a loop
    ansible.builtin.package:
      name: "Package to install: {{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - python